//-----------------------------------------------------------------------
// <copyright file="EnumeratePoolStatesResponse.cs" company="Microsoft">
//     Copyright (c) Microsoft. All rights reserved.
//     Internal use only.
// </copyright>
// <auto-generated /> 
//-----------------------------------------------------------------------

namespace Microsoft.WindowsAzure.Management.Utilities.XblCompute.Contract
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public class XblEnumerateClustersResponse
    {
        [DataMember(Name = "clustersInfo")]
        public List<ClusterInformationEx> ClusterInformationCollection { get; set; }
    }

    /// <summary>
    /// The extended cluster information that gives the gsiname and the variant name in addition to base class information
    /// </summary>
    [DataContract(Namespace = "")]
    public class ClusterInformationEx : ClusterInformation
    {
        /// <summary>
        /// Gets or sets the name of the gsi.
        /// </summary>
        [DataMember(Name = "gsiName")]
        public string GsiName { get; set; }

        /// <summary>
        /// Gets or sets the name of the variant.
        /// </summary>
        [DataMember(Name = "variantName")]
        public string VariantName { get; set; }
    }

    // <summary>
    /// The cluster information response contract for gsms.
    /// </summary>
    [DataContract]
    public class ClusterInformation
    {
        /// <summary>
        /// Gets or sets the cluster id.
        /// </summary>
        [DataMember(Name = "clusterId")]
        public string ClusterId { get; set; }

        /// <summary>
        /// Gets or sets the session id.
        /// </summary>
        [DataMember(Name = "sessionId")]
        public string SessionId { get; set; }

        /// <summary>
        /// Gets or sets the variant id.
        /// </summary>
        [DataMember(Name = "variantId")]
        public string VariantId { get; set; }

        /// <summary>
        /// Gets or sets the gsi id.
        /// </summary>
        [DataMember(Name = "gsiId")]
        public string GsiId { get; set; }

        /// <summary>
        /// Gets or sets the status.
        /// </summary>
        [DataMember(Name = "state")]
        public string State { get; set; }

        /// <summary>
        /// Gets or sets the location.
        /// </summary>
        [DataMember(Name = "location")]
        public string Location { get; set; }

        /// <summary>
        /// Gets or sets the location.
        /// </summary>
        [DataMember(Name = "machineResidence")]
        public string MachineResidence { get; set; }

        /// <summary>
        /// Gets or sets the timestamp at which the state transition happened.
        /// </summary>
        [DataMember(Name = "transitionTimestampUtc")]
        public string TransitionTimestampUtc { get; set; }
    }
}
