//-----------------------------------------------------------------------
// <copyright file="XblEnumerateDiagnosticFilesResponse.cs" company="Microsoft">
//     Copyright (c) Microsoft. All rights reserved.
//     Internal use only.
// </copyright>
// <auto-generated /> 
//-----------------------------------------------------------------------

namespace Microsoft.WindowsAzure.Management.Utilities.XblCompute.Contract
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public class XblEnumerateDiagnosticFilesResponse
    {
        /// <summary>
        /// Gets or sets the continuation token.
        /// </summary>
        [DataMember(Name = "continuationToken")]
        public string ContinuationToken
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets diagnostic files.
        /// </summary>
        [DataMember(Name = "diagnosticFiles")]
        public List<DiagnosticFile> DiagnosticFiles
        {
            get;
            set;
        }
    }

    [DataContract]
    public sealed class DiagnosticFile
    {
        /// <summary>
        /// Gets or sets the filename.
        /// </summary>
        [DataMember(Name = "filename")]
        public string Filename { get; set; }

        /// <summary>
        /// Gets or sets the URL.
        /// </summary>
        [DataMember(Name = "url")]
        public string Url { get; set; }
    }
}